services:
  - type: web
    name: devshowcase-api
    runtime: docker
    dockercontext: ./devshowcase-api
    dockerfilePath: ./devshowcase-api/Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
